import 'dart:io';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:provider/provider.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../models/grievance.dart';
import '../../models/student_profile.dart';
import '../../services/auth_service.dart';
import '../../services/firestore_service.dart';
import '../../services/cloudinary_service.dart';
import '../../services/priority_service.dart';
import '../../utils/constants.dart';

class SubmitGrievanceScreen extends StatefulWidget {
  final StudentProfile? profile;

  const SubmitGrievanceScreen({super.key, this.profile});

  @override
  State<SubmitGrievanceScreen> createState() => _SubmitGrievanceScreenState();
}

class _SubmitGrievanceScreenState extends State<SubmitGrievanceScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();

  String? _selectedCategory;
  bool _isAnonymous = false;
  File? _proofFile;
  String? _proofFileName;
  bool _isSubmitting = false;

  final List<String> _categories = [
    GrievanceCategory.academic,
    GrievanceCategory.hostel,
    GrievanceCategory.financial,
    GrievanceCategory.infrastructure,
    GrievanceCategory.discrimination,
    GrievanceCategory.other,
  ];

  @override
  void dispose() {
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickProofFile() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'jpeg', 'png', 'pdf'],
    );

    if (result != null) {
      if (result.files.single.size > 5 * 1024 * 1024) {
        // 5MB limit
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('File size must be less than 5MB')),
          );
        }
        return;
      }

      setState(() {
        _proofFile = File(result.files.single.path!);
        _proofFileName = result.files.single.name;
      });
    }
  }

  Future<void> _submitGrievance() async {
    if (!_formKey.currentState!.validate()) return;

    if (widget.profile == null && !_isAnonymous) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Profile required for non-anonymous submission'),
        ),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final firestoreService = context.read<FirestoreService>();
      final cloudinaryService = context.read<CloudinaryService>();
      final authService = context.read<AuthService>();

      String? proofUrl;

      // 1. Upload proof if exists
      if (_proofFile != null && widget.profile != null) {
        try {
          final uploadResult = await cloudinaryService.uploadFile(
            file: _proofFile!,
            folder: 'grievance_proofs/${widget.profile!.studentUID}',
            startFileName:
                'Grievance_Proof_${DateTime.now().millisecondsSinceEpoch}_$_proofFileName',
          );
          proofUrl = uploadResult['secure_url'];
        } catch (e) {
          debugPrint('Error uploading proof: $e');
        }
      }

      // 2. Calculate Priority
      final priorityScore = PriorityService.calculatePriorityScore(
        _selectedCategory!,
        _descriptionController.text,
      );

      // 3. Create Grievance Object
      final now = DateTime.now();
      // SLA: 48 hours normally, 24 hours for Critical (>70 score)
      final slaHours = priorityScore >= 70 ? 24 : 48;
      final slaDeadline = now.add(Duration(hours: slaHours));

      // authService captured above
      final currentUser = authService.currentUser;

      if (currentUser == null) throw Exception('User not logged in');

      final grievance = Grievance(
        id: '', // Generated by Firestore
        userId: currentUser.uid, // Firebase Auth UID
        studentUID: widget.profile?.studentUID, // Roll Number
        category: _selectedCategory!,
        description: _descriptionController.text,
        isAnonymous: _isAnonymous,
        proofUrls: proofUrl != null ? [proofUrl] : [],
        status: GrievanceStatus.pending,
        priorityScore: priorityScore,
        submittedAt: now,
        slaDeadline: slaDeadline,
        // assignedTo: null,
        // resolution: null,
      );

      await firestoreService.createGrievance(grievance);

      if (mounted) {
        await showDialog(
          context: context,
          barrierDismissible: false,
          builder: (ctx) => Dialog(
            backgroundColor: Colors.transparent,
            insetPadding: const EdgeInsets.all(24),
            child: Container(
              padding: const EdgeInsets.all(32),
              decoration: BoxDecoration(
                color:
                    Theme.of(context).dialogTheme.backgroundColor ??
                    Theme.of(context).cardColor,
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(
                      alpha: 0.2,
                    ), // Darker shadow for dark mode
                    blurRadius: 20,
                    offset: const Offset(0, 10),
                  ),
                ],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  // Animated Success Icon
                  Container(
                        padding: const EdgeInsets.all(20),
                        decoration: BoxDecoration(
                          color: const Color(0xFF06D6A0).withValues(alpha: 0.1),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(
                          Icons.check_rounded,
                          color: Color(0xFF06D6A0),
                          size: 48,
                        ),
                      )
                      .animate()
                      .scale(duration: 400.ms, curve: Curves.easeOutBack)
                      .then()
                      .shimmer(duration: 1200.ms, color: Colors.white),

                  const SizedBox(height: 24),

                  Text(
                    'Grievance Submitted!',
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                    textAlign: TextAlign.center,
                  ).animate().fadeIn(delay: 200.ms).slideY(begin: 0.2, end: 0),

                  const SizedBox(height: 12),

                  Text(
                    'Your grievance has been received.\n\nPriority Level: ${PriorityService.getPriorityLevel(priorityScore)}\nExpected Resolution: Within $slaHours hours',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.grey[600], height: 1.5),
                  ).animate().fadeIn(delay: 400.ms),

                  const SizedBox(height: 32),

                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: () {
                        Navigator.pop(ctx); // Close dialog
                        Navigator.pop(context); // Close screen
                      },
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        backgroundColor: Theme.of(context).primaryColor,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                      ),
                      child: const Text('Done'),
                    ),
                  ).animate().fadeIn(delay: 600.ms).slideY(begin: 0.2, end: 0),
                ],
              ),
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error submitting grievance: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    if (widget.profile == null) {
      return const Scaffold(body: Center(child: Text('Profile not loaded')));
    }

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text('Submit Grievance'),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              setState(() {
                _descriptionController.clear();
                _selectedCategory = null;
                _isAnonymous = false;
                _proofFile = null;
                _proofFileName = null;
              });
            },
            tooltip: 'Clear Form',
          ),
        ],
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Intro
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Theme.of(
                      context,
                    ).primaryColor.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(
                      color: Theme.of(
                        context,
                      ).primaryColor.withValues(alpha: 0.3),
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.info_outline,
                        color: Theme.of(context).primaryColor,
                      ),
                      const SizedBox(width: 12),
                      const Expanded(
                        child: Text(
                          'Your grievance will be prioritized based on keywords and category. Serious issues are auto-escalated.',
                          style: TextStyle(fontSize: 12),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),

                // Category
                DropdownButtonFormField<String>(
                  initialValue: _selectedCategory,
                  decoration: const InputDecoration(
                    labelText: 'Category',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.category),
                  ),
                  items: _categories
                      .map(
                        (c) => DropdownMenuItem(
                          value: c,
                          child: Text(c.toUpperCase()),
                        ),
                      )
                      .toList(),
                  onChanged: (v) => setState(() => _selectedCategory = v),
                  validator: (v) =>
                      v == null ? 'Please select a category' : null,
                ),
                const SizedBox(height: 16),

                // Description
                TextFormField(
                  controller: _descriptionController,
                  maxLines: 5,
                  decoration: const InputDecoration(
                    labelText: 'Description',
                    hintText: 'Describe your issue in detail...',
                    border: OutlineInputBorder(),
                    alignLabelWithHint: true,
                  ),
                  validator: (v) {
                    if (v == null || v.trim().isEmpty) {
                      return 'Description is required';
                    }
                    if (v.trim().length < 20) {
                      return 'Please provide more detail (min 20 chars)';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Proof Upload
                InkWell(
                  onTap: _pickProofFile,
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      border: Border.all(color: Theme.of(context).dividerColor),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Row(
                      children: [
                        const Icon(Icons.attach_file),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Text(
                            _proofFileName ?? 'Attach Proof (Optional)',
                            style: TextStyle(
                              color: _proofFileName != null
                                  ? Theme.of(context).textTheme.bodyLarge?.color
                                  : Theme.of(context).hintColor,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        if (_proofFileName != null)
                          IconButton(
                            icon: const Icon(Icons.close, color: Colors.red),
                            onPressed: () => setState(() {
                              _proofFile = null;
                              _proofFileName = null;
                            }),
                          ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 8),
                const Text(
                  'Max size: 5MB. Formats: PDF, JPG, PNG',
                  style: TextStyle(fontSize: 12, color: Colors.grey),
                ),

                const SizedBox(height: 16),

                // Anonymous Checkbox
                CheckboxListTile(
                  title: const Text('Submit Anonymously'),
                  subtitle: const Text(
                    'Your name will be hidden from the committee.',
                  ),
                  value: _isAnonymous,
                  onChanged: (v) => setState(() => _isAnonymous = v ?? false),
                  controlAffinity: ListTileControlAffinity.leading,
                  contentPadding: EdgeInsets.zero,
                ),

                const SizedBox(height: 32),

                ElevatedButton(
                  onPressed: _isSubmitting ? null : _submitGrievance,
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    backgroundColor: Theme.of(context).primaryColor,
                    foregroundColor: Colors.white,
                  ),
                  child: _isSubmitting
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Text(
                          'Submit Grievance',
                          style: TextStyle(fontSize: 16),
                        ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
